### PR TITLE
[Dont Merge] stash for help

### PR DESCRIPTION
**Pull request by kylewolfe**
Hello. I know absolutely nothing about OpenGL but I wanted to play around. Would you mind helping me get this example working? I just copied code from g3n/g3nd and g3n/demos to try to get it to work with a gopher.obj that was used in go-qml's examples.

Thanks!

### CODE REVIEW

**Comment by leonsal** [comment]
In the repository: https://github.com/golang-samples/gopher-3d the _obj_ model was
missing the `gopher.mtl` file which describes the materials used in the model.
The file `gopher.stl` is another format not related to the _obj_ format.

We created a new demo and exported from the original `gopher.blend` the `gopher.obj` and `gopher.mtl` files. The demo also includes a camera control a directional light to visualize the model better.
Note: the demo must be run from its directory for it to find the model files.

```
>go get github.com/g3n/demos/gopher3d
>cd <GOPATH>/src/github.com/g3n/demos/gopher3d
>go build
>./gopher3d
```

**Comment by kylewolfe** [comment]
Thanks, I'll have a look at this tonight. Shouldn't obj.Decode have errored from receiving bad input from stl, though?

**Comment by kylewolfe** [comment]
Also, I recommend preserving the LICENSE listed at https://github.com/golang-samples/gopher-3d for the gopher.

**Comment by leonsal** [comment]
Added `README.md` with license. Will check obj.Decode()

**Pull request closed without merging**
